### ISSUE TITLE
Add gitignore to prevent tracking unimportant files

### ISSUE THREAD

**Issue by scottnm** [ULAFF/LAFF-On-PfHP#2]
After compiling the hello world example in week0, I noticed git produced the following output
![image](https://user-images.githubusercontent.com/5483270/59150064-6a3c8780-89d2-11e9-8078-6cd0e8cadf1c.png)

these object and executable files probably shouldn't ever be committed to the source tree.
Recommend adding a simple `.gitignore` file at the root of the project which can tell git to ignore certain files

```
# ignores all object files and executables that may be generated when compiling
*.o
*.x
```

**Comment by rvdg** [comment]
Thank you.  I am a relative ignoramus when it comes to github.  Tend to make a mess of it...
Can you check if I did it right?

**Comment by scottnm** [comment]
Yup it's correct! thanks
